Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Login(IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var username = collection["UserName"].ToString();
                var role = collection["Role"].ToString();
                HttpContext.Session.SetString("SessionUserName", username);
                HttpContext.Session.SetString("SessionRole", role);
                return Redirect("/Product/Index");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("SessionUserName");
            HttpContext.Session.Remove("SessionRole");
            return Redirect("/");
        }
        
    }
}

Controllers/ProductController.cs
using InventoryManagementSystem.BO;
using InventoryManagementSystem.InventoryException;
using InventoryManagementSystem.Models;
using InventoryManagementSystem.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Serilog;

namespace InventoryManagementSystem.Controllers
{


    public class ProductController : Controller
    {
        private readonly ProductBO _productBO;

        public ProductController(ProductBO productRepos)
        {
            _productBO = productRepos;
        }


        public ActionResult Index()
        {
            ViewBag.total = _productBO.TotalProducts();
            ViewBag.lowStock=_productBO.LowStock();
            ViewBag.supplierCount = _productBO.SupplierCount();
            return View();
        }

        //// GET: ProductController/Details/5
        //[Route("~/[controller]/Details")]
        //[Route("~/[controller]/Details/{id:PositiveConstraint}")]
        public ActionResult Details(int id)
        {
            Log.Information("Fetch By Id Method Invoked");
            try
            {
                var product = _productBO.FetchProductById(id);
                return View("Details", product);
            }
            catch (ArgumentException ex)
            {
                Log.Error(ex, "Id Invalid");
                ViewData["Response"] = "Enter the Valid Product Id";
                return View("Details");
            }
            catch (InventoryManagementException)
            {                
                ViewData["Response"] = "Enter the Product Id";
                return View("Details");
            }
            catch (InventoryNotFoundException ex)
            {
                Log.Error(ex, "Id Not Found");
                ViewData["Response"] = "Id Not Found!!!";
                return View("Details");
            }
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return View("Details");
            }
}

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Log.Information("Create Method Invoked");
                    bool flag = _productBO.InsertProduct(product);

                    if (flag)
                    {
                        ViewData["Response"] = "Product Added SuccessFully";
                    }                    
                    return View("Create");
                }
                else
                {
                    return View();
                }
            }
           
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while Creating Product");
                ViewData["Response"] = "An error occurred while creating product . Please try again later or contact admin.";
                return View();
            }
            catch (InventoryManagementException)
            {
                ViewData["Response"] = "Enter the BarCode As Unique";
                return View();

            }
        }

        // GET: ProductController/Edit/5
        //[Route("~/[controller]/Edit")]
        //[Route("~/[controller]/Edit/{id:PositiveConstraint}")]


        public ActionResult Edit(int id)
        {

            Log.Information("Edit Method Invoked");
            try
            {
                var product = _productBO.FetchProductById(id);
                return View("Edit", product);
            }
            catch (ArgumentException ex)
            {
                Log.Error(ex, "Id Invalid");
                ViewData["Response"] = "Enter the Valid Product Id";
                return View("Edit");
            }
            catch (InventoryManagementException)
            {
                ViewData["Response"] = "Enter the Product Id";
                return View("Edit");
            }
            catch (InventoryNotFoundException ex)
            {
                Log.Error(ex, "Id Not Found");
                ViewData["Response"] = "Id Not Found!!!";
                return View("Edit");
            }
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return View("Edit");
            }
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Product product)
        {
            if (ModelState.IsValid)
            {
                Log.Information("Edit Method Invoked");
                bool flag = _productBO.UpdateProduct(product);

                if (flag)
                {
                    ViewData["Response"] = "Product Updated SuccessFully";
                }
                else
                {
                    ViewData["Response"] = "Product Failed to Update";
                }
                return View("Edit", product);
            }
            return View();


        }

        //[Route("~/[controller]/Delete")]
        //[Route("~/[controller]/Delete/{id:PositiveConstraint}")]
        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {

            Log.Information("Delete Method Invoked");
            try
            {
                var product = _productBO.FetchProductById(id);
                return View("Delete", product);
            }
            catch (ArgumentException ex)
            {
                Log.Error(ex, "Id Invalid");
                ViewData["Response"] = "Enter the Valid Product Id";
                return View("Delete");
            }
            catch (InventoryManagementException)
            {
                ViewData["Response"] = "Enter the Product Id";
                return View("Delete");
            }
            catch (InventoryNotFoundException ex)
            {
                Log.Error(ex, "Id Not Found");
                ViewData["Response"] = "Id Not Found!!!";
                return View("Delete");
            }
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return View("Delete");
            }
        }

        

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Product product)
        {
            Log.Information("Delete Method Invoked");
            bool flag = _productBO.DeleteProduct(id);


            if (flag)
            {
                ViewData["Response"] = "Product Deleted SuccessFully";
            }
            else
            {
                ViewData["Response"] = "Product Failed to Delete";
            }
            return View("Delete");
        }
        [HttpGet]
        public ActionResult FetchAll()
        {
            try { 
            Log.Information("FetchAll Method Invoked");
            IEnumerable<Product> products = _productBO.FetchAllProducts();
            return View("FetchAll", products);
        }
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return Redirect("Create");
            }

        }
        public ActionResult FetchProductWithSupplier()
        {
            try
            {
                Log.Information("Fetch All Product Using Join Method Invoked");
                var products = _productBO.FetchAllProductUsingJoin();
                return View("FetchProductWithSupplier", products);
            }
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return Redirect("Create");
            }

        }

        public ActionResult FetchProductsUsingFilter()
        {
            try
            {
                Log.Information("Fetch Products Using Filter Method Invoked");
                IEnumerable<Product> products = _productBO.FetchProductsUsingFilter();
                return View("FetchProductsUsingFilter", products);
            }
           
            catch (SqlException ex)
            {
                Log.Error(ex, "Error occurred while fetching product details");
                ViewData["Response"] = "An error occurred while fetching product details. Please try again later or contact admin.";
                return Redirect("Create");
            }
        
        }
        public ActionResult FetchProductUsingAssociation(string productName, int quantity)
        {
            try
            {
                Log.Information(productName,quantity);
                Log.Information("Fetch Product Using Association Method Invoked");
                IEnumerable<Product> products = _productBO.FetchProductUsingAssociation(productName, quantity);
                return View("FetchProductUsingAssociation", products);
            }
            catch (SqlException ex)
            {

Views/Shared/PagenotFoundError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "_MyLayout";
}
<html>
    <head>
        <title>PageNotFoundError</title>
    </head>
    <body>
        <h1>Invalid URL !!! Please ReCheck Your Url</h1>
    </body>
</html>

Views/Shared/UnAuthorizedError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


@{
    Layout = "_MyLayout";
}
<html>
<head>
    <title>UnAuthorizedError</title>
</head>
<body>
    <h1>You Can not Enter. Please Contact Admin</h1>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InventoryManagementSystem</a>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InventoryManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>   
    <header>
        <nav class="navbar navbar-expand-md navbar-light">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <img src="/logo.png" alt="Inventory Logo" asp-append-version="true" class="logo">
                    </div>
                    <div class="col text-center">
                        <h1 class="head">Inventory Pro</h1>
                    </div>
                </div>         
        @{
        string? username = @HttpContextAccessor?.HttpContext?.Session.GetString("SessionUserName");
        string? role = @HttpContextAccessor?.HttpContext?.Session.GetString("SessionRole");
        }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
             </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">            
                    <ul>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Details">Details</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Edit">Edit</a>
                         </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Delete">Delete</a>
                        </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" >
                            More
                        </a>
                        <div class="dropdown-menu" >
                            <a class="nav-link " asp-controller="Product" asp-action="FetchAll" >FetchAll</a>
                            <a class="nav-link " asp-controller="Product" asp-action="FetchProductsUsingFilter" >FetchAll Filter</a>
                            <a class="nav-link " asp-controller="Product" asp-action="FetchProductUsingAssociation" >FetchAllAssociation</a>
                            <a class="nav-link " asp-controller="Product" asp-action="FetchProductWithSupplier">FetchAll Join</a>
                        </div>
                    </li>
                     <li class="nav-item">
                         @if(!string.IsNullOrEmpty(username))
                         {
                            <li class="nav-item dropdown">
                                 <a class="nav-link dropdown-toggle" title="@username,@role" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" >
                                        @username
                                 </a>
                                <div class="dropdown-menu">
                                    <a class="nav-link " asp-controller="Login" asp-action="Logout">Logout</a>
                                </div>
                            </li>
                         } 
                         else{
                                <a class="nav-link " asp-area="" asp-controller="Login" asp-action="Login"> Sign In</a>
                        }
                     </li>
                        
                    </ul>                    
            </div>
            </div>
        </nav>
    </header>
            <div class="container-fluid">
                <div class="row">
                    <main role="main" class="col-md-12">
               @RenderBody()
            </main>
    </div>
  </div>
  <footer>
        <img src="/footerlogo.png" alt="Mobile Shop Logo" class="footerlogo">    <p>&copy; 2024 <span> Inventory Pro</span>. All rights reserved.</p>
        <p>Developed by<strong><span style="color: #e7962c;"> Aravindha samy</span></strong></p>
  </footer>     
</body>
@RenderSection("Scripts", required: false)
</html>